---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Сервисы Локального ИИ и Базы Знаний:
    - Локальный ИИ AnythingLLM:
        href: "https://krinikspc.forest-ratio.ts.net/"
    - База Знаний Kiwix:
        href: "https://krinikspc.forest-ratio.ts.net/wiki"
